### ISSUE TITLE
tooltip not auto disapper

### ISSUE THREAD

**Issue by Leiyi548** [vran-dev/obsidian-contribution-graph#26]
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/76139422/13762dce-7286-418e-a169-7eaa15a050e5)

**Comment by vran-dev** [comment]
thanks,  issue has been fixed at #11, and will be released in the next version

**Comment by Leiyi548** [comment]
> thanks, issue has been fixed at #11, and will be released in the next version

OK, thank you for fixing the bug so quickly.

**Comment by vran-dev** [comment]
close issue because the issue had been fixed and released at [0.5.0](https://github.com/vran-dev/obsidian-contribution-graph/releases/tag/0.5.0)
