### ISSUE TITLE
请问是否可以设置标题的大小，或是字体的大小？

### ISSUE THREAD

**Issue by i-iooi-i** [vran-dev/obsidian-contribution-graph#33]
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/510b126f-ca91-447f-ba12-ed1fe5db8051)

大佬，请问是否可以设置标题的大小尺寸呢？ 我切换了几款主题，发现标题大小都是一样的，故排除是主题的问题了。
因为若是无法调整字体大小，在插入到文字内容页面，整体美观度可能会因欠缺自定义字体大小而稍显不和谐。

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/1cde86f9-d3ff-46cf-a918-1518bf19ddcb)
另外还发现一点小瑕疵，在删除标题的情况下，再次进入编辑模式，右上角的三条横杠会跟月份有些小穿插。

希望大佬打赏页面添加个支付宝或者贝宝，Buy Me a Coffee 好像国内有些银行不支持哦。
真的很感谢大佬开发这个让普通人轻松上手的漂亮热力图插件，希望阔以尽快上线商店，造福更多玩家。🫡🫡🫡

**Comment by vran-dev** [comment]
@i-iooi-i 

Hi i-iooi-i

- 目前的字体大小需要再源码里面去调整 fontSize 属性，默认是 1.5em（em 是单位），你可以自己试着去增加或者减小该数值。（后续我会提供可视化的更改界面）

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/73a69dec-fa42-43dd-aa59-9fb7dd88e176)

- 这是一个很 trick 的问题，似乎加高高度就能解决，但那样又会导致上方留白，我会尽量去平衡一下

- 赞赏渠道的话，可以通过[公众号文章页](https://mp.weixin.qq.com/s/2OmvDuIZhlDWlNoqRj2r_A)的【喜欢】来支持

**Comment by i-iooi-i** [comment]
> @i-iooi-i
> 
> Hi i-iooi-i
> 
> * 目前的字体大小需要再源码里面去调整 fontSize 属性，默认是 1.5em（em 是单位），你可以自己试着去增加或者减小该数值。（后续我会提供可视化的更改界面）
> 
> ![image](https://private-user-images.githubusercontent.com/12870335/294728012-73a69dec-fa42-43dd-aa59-9fb7dd88e176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MzY3MDcsIm5iZiI6MTcwNDYzNjQwNywicGF0aCI6Ii8xMjg3MDMzNS8yOTQ3MjgwMTItNzNhNjlkZWMtZmE0Mi00M2RkLWFhNTktOWZiN2RkODhlMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE0MDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDRjZTliZWQyZDcyZTgyYjY2NThjOTI3NTVjMGNiYTc2NWMyYjQ0MzQ2MTJhZDg3NDIyZWI3YThmZmYzZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zxk3rWo0uP60yHlzoQhKxRtTVZqSl0Fn8-jsZ9iVgKw)
> 
> * 这是一个很 trick 的问题，似乎加高高度就能解决，但那样又会导致上方留白，我会尽量去平衡一下
> * 赞赏渠道的话，可以通过[公众号文章页](https://mp.weixin.qq.com/s/2OmvDuIZhlDWlNoqRj2r_A)的【喜欢】来支持

好嘞，感谢大佬答复。
我就是吹毛求疵一下，hhhh，插件已经很棒啦，再次感谢！🌹

**Comment by vran-dev** [comment]
release at  [0.6.0](https://github.com/vran-dev/obsidian-contribution-graph/releases/tag/0.6.0)
