### ISSUE TITLE
启动OB热力图信息不显示

### ISSUE THREAD

**Issue by i-iooi-i** [vran-dev/obsidian-contribution-graph#41]
![动画](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/fd02d043-4ea5-42bd-b9e1-21a11dbfd4ab)

遇到一个小问题哈，当把热力图放在首页，启动OB的时候热力图信息是不展示的。
只有切换一下页面，再切回来，热力图信息才会被加载出来哦。

**Comment by vran-dev** [comment]
@i-iooi-i  

这个问题我没有复现出来，方便通过公众号私信我加 v 聊吗？

**Comment by gradypark86** [comment]
我也发现了这一问题，表现为热力图方块在阅读视图下不显示，右下角“more”会换行显示，切换到编辑模式可正常显示，如图所示。

我这边试了一下，发现仅出现在设置为 homepage 的页面中，在 Obsidian 启动时自动打开的情况下出现这一问题。如果手动在新标签页打开此 homepage 页面，则所有视图显示正常。

<img width="911" alt="image" src="https://github.com/vran-dev/obsidian-contribution-graph/assets/39909237/73baeb85-2460-4dfe-9e9d-381383f8f6f6">

**Comment by vran-dev** [comment]
@gradypark86  用的最新版吗？

**Comment by i-iooi-i** [comment]
> @gradypark86 用的最新版吗？

大佬，本加班狗还在加班🐕，可能暂时没那么快回家，哈哈哈🙈

我刚才用了最新发布的版本，也是同样的问题。
我以为是插件冲突，但是我关闭了其他不相干的插件，问题依然存在。

大佬可以新建一个页面，添加一个热力图，然后关闭OB，再启动OB，应该就能看到了。

![动画](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/398edf4c-a18d-4857-9118-b387fcd3762d)
我这边是每次得切换一下页面才能刷新出来的。

**Comment by i-iooi-i** [comment]
![动画1](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/2342b8c4-0ac8-4d54-ba1b-92e30f21c336)

或者有没有可能是 Dataview 插件的设置问题导致的呢？
对了，我的OB版本也是最新的。

**Comment by gradypark86** [comment]
我也是继续用新版本试了一下，发现和页面是否是 homepage 没关系，只要是满足：关闭 Obsidian 前当前页面存在热力图，那么重新打开 Obsidian 时，当前页面的热力图方块就不显示了。之前是设置成了 homepage 在 Obsidian 启动时默认打开，所以也会出现这一问题。

另外我还试了一下把两个笔记中插入热力图后分栏显示，重启 Obsidian 后，2 个笔记的热力图方块都是不显示的。在新页面打开该笔记或者修改 contribution-graph 的任何一个设置都可以重新显示出来。


https://github.com/vran-dev/obsidian-contribution-graph/assets/39909237/a308c7f5-b34d-49d9-a20c-246de5863eb9

**Comment by vran-dev** [comment]
@i-iooi-i  @gradypark86   已修复并发布在 [0.6.2](https://github.com/vran-dev/obsidian-contribution-graph/releases/tag/0.6.2)

**Comment by i-iooi-i** [comment]
阔以啦大佬，牛的牛的。
希望可以早日上线官方商店，造福全人类！ 🫡🫡🫡
