### ISSUE TITLE
单元格指示器 无法关闭

### ISSUE THREAD

**Issue by i-iooi-i** [vran-dev/obsidian-contribution-graph#46]
![动画](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/05436282-608e-42d6-85d8-4447b18270e8)

大佬,我又来提BUG啦. 

在样式设置里面,取消勾选"单元格指示器",在预览的时候指示器确实不显示.
但是点击确定之后,页面上依然显示指示器.

另外,公众号已关注,哈哈哈.

**Comment by i-iooi-i** [comment]
![动画](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/08dcc29b-c9a6-4c23-be73-b58ea6c750b9)
另外，在点开热力图的内容之后，再次点击，内容没有被折叠回去。
目前只能通过切换页面才可以折叠回去。

**Comment by vran-dev** [comment]
- 在【阅读模式】下做的更改目前是不生效的
- 单元格的内容隐藏功能已经实现了，下个版本见
