### ISSUE TITLE
请问是否可以考虑缩减一下行高

### ISSUE THREAD

**Issue by i-iooi-i** [vran-dev/obsidian-contribution-graph#47]
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/e961b823-68de-46d5-b369-25e0d42e66dd)
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/1827701/575f4ab3-f801-4150-a2f3-ba4fb773efe6)

请问是否可以考虑缩减一下行高, 主要是下面这块区域空白的面积有点大.  
当下方填写文字内容以后, 这个热力图表因为行距过大的问题,会显得在上方很孤立, 从页面上看跟文字排版内容也不是很相称蛤.

**Comment by vran-dev** [comment]
#51
