### ISSUE TITLE
不能渲染什么都没干的一天的“颜色”

### ISSUE THREAD

**Issue by semidry** [vran-dev/obsidian-contribution-graph#53]
我使用双色配色（蓝->红），但是我发现当我一天什么都没干的时候，它什么颜色的不显示（按照我的逻辑，其应该显示为深蓝色而不是无颜色，这样看起来这一天我看似做了不多不少的工作）。不知道这是obsidian的限制还是您没有考量，希望增加对贡献数为0时的显示。
<img width="1080" alt="Snipaste_2024-01-28_01-34-29" src="https://github.com/vran-dev/obsidian-contribution-graph/assets/98629134/369f0025-3c20-4a12-9919-af5c5c27c809">
<img width="124" alt="Snipaste_2024-01-28_01-34-36" src="https://github.com/vran-dev/obsidian-contribution-graph/assets/98629134/8bc84e81-c201-4794-bf95-d8c5505a139d">

**Comment by vran-dev** [comment]
@semidry  下载最新版试试
