### ISSUE TITLE
week indicator is not aligned if change cell's height

### ISSUE THREAD

**Issue by aggjjfd** [vran-dev/obsidian-contribution-graph#65]
在git视图下，调整contributionGraph代码块中cellStyle部分minHeight的数值后，图表左侧的.cell.week-indicator类仍保持默认高度，导致星期的文字对不上格子。

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/47317052/0b7061bc-606d-4d25-bbe6-1f9f13087b85)

**Comment by vran-dev** [comment]
has been fixed at #64, and will be released in the next version.

**Comment by vran-dev** [comment]
released at 0.9.0
