### ISSUE TITLE
Property-based habit tracking using property value as count

### ISSUE THREAD

**Issue by rtm** [vran-dev/obsidian-contribution-graph#69]
My use case is to create a heat map for information represented as properties in notes either in the metadata or inline. For instance, a note with a particular day as its title might have a property called `exercise` with the value of 30 meaning 30 minutes. I'm sure I can do this somehow using the API, but is there some simpler way or can you provide some guidance?

**Comment by vran-dev** [comment]
> My use case is to create a heat map for information represented as properties in notes either in the metadata or inline. For instance, a note with a particular day as its title might have a property called `exercise` with the value of 30 meaning 30 minutes. I'm sure I can do this somehow using the API, but is there some simpler way or can you provide some guidance?

Currently, only task data is supported for statistics based on `dataview inline property`.

but If you want to generate a heat map based on the page's property (yaml frontmatter)

- set source to `""`, means query all pages
- set count field to `page property` and value to `exercise`

it means generating heatmap by exercise value from the page which has `exercise` property

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/9c545b59-2811-4d9e-a0fd-6a8ba4e22776)

**Comment by rtm** [comment]
Thanks, I got it!

Actually though what I'd really like to do is to use the **value** of the property as the quantity, whereas as far as I can tell right now it's just treating the presence of the property as a "1". Any ideas?

**Comment by vran-dev** [comment]
It's no problem here, you can click the cell to show details

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/ab6004e7-78c8-4b48-aad4-321aec847aa2)
