### ISSUE TITLE
如何实现按天统计输入字数或者创建文件数？

### ISSUE THREAD

**Issue by karterotte** [vran-dev/obsidian-contribution-graph#70]
如题。是否可以设置指定文件夹的过滤条件？

**Comment by vran-dev** [comment]
- 输入字数不支持，因为插件没有记录相关的数据，ob 自身也没有这样的数据
- 按天统计的文件的话：`日期字段` 选择 `文件创建日期`,  `打分属性` 选择 `默认`，这样就是基于每天的创建的文件来生成的热力图了
