### ISSUE TITLE
是否有打算增加过滤目录的功能？

### ISSUE THREAD

**Issue by wx-wangxue** [vran-dev/obsidian-contribution-graph#71]
Obsidian仓库中有些存放的是非笔记文件，例如组件或者样式使用的JS，这些目录一般不希望计入统计中。
现在只能将想要被统计的目录一个个录入，但是如果文件太多这里录入比较麻烦。
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/82809830/e2917f6c-ec25-4771-83a5-a6b411e3722d)

**Comment by vran-dev** [comment]
支持的，参考文档：https://blacksmithgu.github.io/obsidian-dataview/reference/sources/#combining-sources

另外，目前只会统计 md 文件的，不会涉及到非  md
