### ISSUE TITLE
[feature request]  Number Properties Display

### ISSUE THREAD

**Issue by dr-buhu** [vran-dev/obsidian-contribution-graph#73]
It'd be nice if Higher Numbers in the numbers property would be displayed on the Heatmap.

![grafik](https://github.com/vran-dev/obsidian-contribution-graph/assets/148866368/ffde07bd-1413-4380-a857-eb44dc9936c3)

**Comment by vran-dev** [comment]
good idea, I will design solutions

**Comment by dr-buhu** [comment]
> good idea, I will design solutions

Thank you so much for adding it!
