### ISSUE TITLE
同時支援透過 Task tag 跟 page tag 過濾 task

### ISSUE THREAD

**Issue by edwardsayer** [vran-dev/obsidian-contribution-graph#81]
當 source 選擇 "All Task"，Filter 選擇 Contains Any Tag: `#sometag` 時，
這樣會過濾出 task 本身有 `#sometag` 的 task.
但如果 `#sometag` 是寫在 page 層級，就過濾不出來了。
有辦法過濾出標在 page 層級的 tag 的 task 嗎?

**Comment by vran-dev** [comment]
set source to `Task in Specific Page`

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/aec068e9-9c12-4c7c-af89-ef9791e8e344)

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/29974c38-cea6-46cc-bb83-c35a103702ab)

**Comment by edwardsayer** [comment]
謝謝您的回覆，我知道這個功能。
但我想建議的功能是，可以過濾出 task 本身有 #sometag **或** page 含有 #sometag 的 task.
原因是有些 task, 是在規劃階段就安排好的，會放在專屬的 project 頁面，這時我會在該頁面加上一個 tag, 例如 #clientTask,
而有些 task 則是臨時性的作業，我會放在 daily note 中，這時候我會在該作業本身加上一個 tag, 例如 #clientTask,
目前這個套件只能達到其中一種過濾功能，而我想建議的則是可以同時支援上述兩種功能!

**Comment by edwardsayer** [comment]
Thanks for your answer.
After test. It does what i need.
To illustrate, i capture some pics below:
1) putting tag in task or page level:
![圖片](https://github.com/vran-dev/obsidian-contribution-graph/assets/98105/fa43bc45-91bc-41c8-a9bb-ad624b73c9f6)
2) set source to Task in Specific Page and assign tag:
![圖片](https://github.com/vran-dev/obsidian-contribution-graph/assets/98105/2abd72c8-5f2a-490d-94d9-675388951746)
3) this plugin can filtered tasks by tag in  task or page level:
![圖片](https://github.com/vran-dev/obsidian-contribution-graph/assets/98105/44bb91a4-44cd-4986-83fd-ff9c596200bf)

**Comment by edwardsayer** [comment]
Since it works as expected, I'm closing this issue.
