### ISSUE TITLE
[bug] UI is not rendered correctly on iOS

### ISSUE THREAD

**Issue by Enteleform** [vran-dev/obsidian-contribution-graph#83]
The labels and legend are rendered, but none of the cells are rendered.

# iOS

![iOS](https://github.com/vran-dev/obsidian-contribution-graph/assets/10906415/b7941f86-0f8a-4589-9862-e66a686c2008)

# Windows

![Windows](https://github.com/vran-dev/obsidian-contribution-graph/assets/10906415/94aa1f9f-80c8-4c9a-a13c-95d7965fc592)

**Comment by vran-dev** [comment]
What is your version of obsidian? try to update obsidian to latest version

**Comment by Enteleform** [comment]
I didn't run an update but maybe one went through automatically.  It seems to be working now.
