### ISSUE TITLE
[feature request] support inline properties in addition to page properties

### ISSUE THREAD

**Issue by benjaminparry** [vran-dev/obsidian-contribution-graph#84]
Firstly, congratulation on creating an increadibly useful and customisable plugin.

As far as I can see from the docs and from my own experimentation the plugin seems to support frontmatter page properties and not inline properties, for example:

Plugin supports
```
---
habit_to_track: 1
---
```

Plugin doesn’t support
```
habit_to_track:: 1
```

Is this correct?

If so, this isn’t Is there any plan to support inline properties as well? I appreciate this might be a considerable undertaking but I thought I would check before considering making any changes to my workflow.

Many thanks again for your contribution to the Obsidian plugin community.

**Comment by vran-dev** [comment]
As long as dataview supports it, there is no problem. Refer to the following example

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/9ad96a6c-c4a5-4578-8f91-0c577d49159e)

![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/12870335/dec43b9d-9abc-4ba3-a38c-60266705259f)

**Comment by benjaminparry** [comment]
That’s fantastic and thought that would be the case. I don’t know how I missed trying that 🤦. Thanks so much, closing the issue.
